version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: brain_agriculture_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brain_agriculture_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brain_agriculture_api
    command: yarn start:dev
    ports:
      - '3333:3333'
    volumes: []
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/brain_agriculture_db
      NODE_ENV: development
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
